version: '3.0'

services:

  # rasa_el:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile_rasa
  #   ports:
  #   - "5005:5005"
  #   volumes:
  #   - ".:/app/"   #gia na parei ta arxeia kai to model
  #   command: train --domain domain.yml --data data --out models

  rasa_el:
    build:
      context: ./
      dockerfile: Dockerfile_rasa
    ports:
    - "5005:5005"
    volumes:
    - ".:/app/"   #gia na parei ta arxeia kai to model
    command: ["run", "--enable-api", "-p", "5005"]

  action-server-el:
    build:
      context: ./
      dockerfile: Dockerfile_rasa_sdk
    ports:
      - 5055:5055
    volumes:
      - ./actions:/app/actions
    command: ["start", "--actions", "actions", "-p", "5055"]
