version: '3.0'

services:

  # rasa:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile_rasa
  #   ports:
  #   - "5006:5006"
  #   volumes:
  #   - ".:/app/"   #gia na parei ta arxeia kai to model
  #   command: train --domain domain.yml --data data --out models

  rasa:
    build:
      context: ./
      dockerfile: Dockerfile_rasa
    ports:
    - "5006:5006"
    volumes:
    - ".:/app/"   #gia na parei ta arxeia kai to model
    command: ["run", "--enable-api", "-p", "5006"]

  action-server:
    build:
      context: ./
      dockerfile: Dockerfile_rasa_sdk
    ports:
      - 5056:5056
    volumes:
      - ./actions:/app/actions
    command: ["start", "--actions", "actions", "-p", "5056"]
